### ISSUE TITLE
图标在IE8下显示不正常

### ISSUE THREAD

**Issue by aiolos2008** [MichealWayne/svgs2fonts#1]
![20190709105809](https://user-images.githubusercontent.com/2800848/60856173-dd872280-a238-11e9-96e1-dc900f07b6bb.jpg)

**Comment by MichealWayne** [comment]
IE8 对font-face的兼容表现不是很好，通过伪元素设置content的font-face在IE8上并不兼容，可换成unicode的形式。如
``` html
<em class="u-iconfont">&#10000;</em>
```

[font-face兼容情况>>](https://caniuse.com/#search=font-face)
![image](https://user-images.githubusercontent.com/16474680/60857135-11177c00-a23c-11e9-838a-3e76ad6c4554.png)
