### ISSUE TITLE
svgs2fonts.js下的getIconUnicode方法有点问题

### ISSUE THREAD

**Issue by super3H** [MichealWayne/svgs2fonts#3]
对[一]进行unicode编码变成了[鰠]

**Comment by MichealWayne** [comment]
getIconUnicode(name) 的入参name是啥呢？:sweat_smile:

**Comment by MichealWayne** [comment]
getIconUnicode作用是将icon进行字体转换时进行unicode匹配，因为需要避开常用字所以默认起始为10000，该方法无实际编码意义
