### ISSUE TITLE
用ie8浏览器打开生成的demo html，图标显示为中文乱码

### ISSUE THREAD

**Issue by LiangQingHao** [MichealWayne/svgs2fonts#5]
![image](https://user-images.githubusercontent.com/52127787/146290500-472e8b11-350c-496d-af02-98d986b2b11c.png)
![image](https://user-images.githubusercontent.com/52127787/146290526-f2f10420-ffb9-4bf1-853f-88f213697345.png)
![image](https://user-images.githubusercontent.com/52127787/146290602-d1446aec-fb0a-43f6-b0e1-2a84199d6a4b.png)

**Comment by MichealWayne** [comment]
可以通过修改IE的字体配置修复（增加参数t）：
``` css
@font-face {
  ...
  url('myIconfont.eot?t=1#IEfix') format('embedded-opentype'),  /* IE6-IE8*/
  ...
}
```

npm下版本（1.0.6）也将修复此问题，感谢反馈

**Comment by LiangQingHao** [comment]
@MichealWayne 
增加参数t也不可以，我是这么解决的：
`@font-face {
            font-family: 'myIconfont';
            src: url('myIconfont.eot?');
            src: url('myIconfont.eot?#IEfix') format('embedded-opentype'), /* IE6-IE8 */
            url('myIconfont.woff2?') format('woff2'), /*w3c*/
            url('myIconfont.woff?') format('woff'), /*w3c*/
            url('myIconfont.ttf?') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
            url('myIconfont.svg?') format('svg');
            font-weight: normal;
            font-style: normal;
            font-display: block;
        }`

**Comment by MichealWayne** [comment]
好的，再次感谢反馈 😄
