### ISSUE TITLE
生成的图标太小，而且不能保持原图标的颜色

### ISSUE THREAD

**Issue by LiangQingHao** [MichealWayne/svgs2fonts#6]
@MichealWayne 
看下面图片，生成的图标并没有保持原图标的大小，颜色也变了，能不能保持原svg的大小和颜色呢，这样就可以直接使用了。
![image](https://user-images.githubusercontent.com/52127787/146298261-65f843ca-19df-4db8-a920-3366546ae537.png)

**Comment by MichealWayne** [comment]
@LiangQingHao 展示大小 font-size 和 svg 原文件有关，可以的话麻烦提供几个svg文件我看下是什么原因。（邮箱michealwayne@163.com）

**Comment by Enjoy-li** [comment]
能否生成**相应的CSS文件**，这样，便于直接被引入使用，避免更新后要手动复制粘贴，此外，把初始化时的options，带到new SVGIcons2SVGFont({})，有更大的配置空间

**Comment by MichealWayne** [comment]
@Enjoy-li 感谢反馈，css文件分离 & options透传将于本月2.0.1版本带上:smile:
